sylius 1.12 support
monsieurbiz/SyliusHomepagePlugin pull request #32
Opened 2023-03-31 10:47 UTC by clairecoloma

Update for Sylius 1.12 :)

2023-03-31 16:17 UTC, jacquesbh requested changes
Just a few changes at first. Let's see how the tests react.

Also I'll run the project locally to give it a try in 1.12!

2023-03-31 16:17 UTC, jacquesbh commented on .github/workflows/tests.yaml
> +        - uses: actions/setup-node@v3
```suggestion
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
```

2023-03-31 16:17 UTC, jacquesbh commented on .php-version.dist
>  8.0
```suggestion
```

2023-03-31 20:54 UTC, clairecoloma commented
Changes done :D

2023-04-26 10:18 UTC, maximehuran approved these changes

2023-05-24 12:21 UTC, delyriand approved these changes

2023-05-24 12:29 UTC, merged

2023-05-24 12:29 UTC, delyriand commented
Thanks, @clairecoloma!